### ISSUE TITLE
Project Proposal  - Access Review and Edit

### ISSUE THREAD

**Issue by CleeMe** [lc-liftoff-alex-group-three/liftoff-group-three#1]
**Access, Edit and Propose **

Link to the working Google Doc we are using to build our Project Proposal

https://docs.google.com/document/d/16NVxXf07pgCzDBtlZJX5E56FarzIxcFW1rYZJdkUNwA/edit#heading=h.8gsuogxpdil2

**Comment by specialtas** [comment]
Designing an app to make eating fruits and vegetables fun for kids ! Here's a suggested flow for the app:

1. **Welcome Screen:**
   - Introduce the app and its purpose.
   - Have an option for the parent to create an account or log in.

2. **Parent Account Creation/Login:**
   - Parents can create an account with necessary information.
   - Secure login for parents.

3. **Parent Dashboard:**
   - Overview of their child's progress.
   - Set goals for the child (daily or weekly fruit/vegetable intake, exploring new foods, etc.).
   - Access to nutritional information and tips.

4. **Child Login:**
   - Child-friendly login with simple, colorful interface.

5. **Dragon Creation Page:**
   - Child can create their dragon character.
   - Choose dragon name and initial features.

6. **Daily Tracking Page:**
   - Daily blank slate for the dragon.
   - Child logs the foods they eat, mark if they liked them, and any other notes.
   - Display nutritional information and benefits of the chosen food colors.

7. **Dragon Customization Page:**
   - As the child eats different colored foods, options for dragon customization unlock.
   - Add features like skin color, eyes, hair, wardrobe, accessories, etc.(I think these can be drop down menus because we learned how to make them and might be easier for now than clicking icons)
   - Include a "Mystery Reward" section(drop down menu with flashy accessories or gold teeth) for trying new foods.

8. **Dragon Showcase:**
   - Page where the child can see their dragon's progression throughout the week.
   - At the end of the week, all unlocked attributes are available for play. This gives them the chance to make their most colorful dragon.

9. **Goal Achievement Page:**
   - Show when the child reaches their goals.
   - Unlock new environments for the dragon based on achievements.

10. **Learning and Exploration:**
    - Dragon visits different countries, learns recipes, and collects colorful foods.
    - Provide educational content for both parents and children about the health benefits of various foods.

11. **API Integration/Database:**
    - Integrate an API to track date, time, and healthful information.
    - Use a database to store dragon images with various attribute combinations.

12. **Settings:**
    - Parental controls, notifications, and app preferences.

13. **Logout:**
    - Easy logout option for both parents and children.

Ensure that the app's design is intuitive, colorful, and child-friendly. Use gamification elements to make the experience enjoyable for kids and encourage healthy eating habits. Regularly update the app with new features to keep the children engaged.

**Comment by CleeMe** [comment]
https://docs.google.com/document/d/16NVxXf07pgCzDBtlZJX5E56FarzIxcFW1rYZJdkUNwA/edit#heading=h.8gsuogxpdil2

link to project proposal
